export const CURRENT_WEATHER_REQUEST = "CURRENT_WEATHER_REQUEST";
export const CURRENT_WEATHER_REQUEST_SUCCESS = "CURRENT_WEATHER_REQUEST_SUCCESS";
export const CURRENT_WEATHER_REQUEST_FAIL = "CURRENT_WEATHER_REQUEST_FAIL";
export const CURRENT_5DAY_FORCAST_REQUEST = "CURRENT_5DAY_FORCAST_REQUEST";
export const CURRENT_5DAY_FORCAST_REQUEST_SUCCESS = "CURRENT_5DAY_FORCAST_REQUEST_SUCCESS";
export const CURRENT_5DAY_FORCAST_REQUEST_FAIL = "CURRENT_5DAY_FORCAST_REQUEST_FAIL";
export const UPDATE_CHOOSEN_CITY = "UPDATE_CHOOSEN_CITY";
export const UPDATE_TEMP_SCALE = "UPDATE_TEMP_SCALE";
