export const LOCATION_AUTOCOMPLETE_REQUEST = "LOCATION_AUTOCOMPLETE_REQUEST";
export const LOCATION_AUTOCOMPLETE_REQUEST_SUCCESS = "LOCATION_AUTOCOMPLETE_REQUEST_SUCCESS";
export const LOCATION_AUTOCOMPLETE_REQUEST_FAIL = "LOCATION_AUTOCOMPLETE_REQUEST_FAIL";
export const UPDATE_LOCATION_CITY = "UPDATE_LOCATION_CITY";
export const LOCATION_BY_LAT_LON_REQUEST = "LOCATION_BY_LAT_LON_REQUEST";
export const LOCATION_BY_LAT_LON_REQUEST_SUCCESS = "LOCATION_BY_LAT_LON_REQUEST_SUCCESS";
export const LOCATION_BY_LAT_LON_REQUEST_FAIL = "LOCATION_BY_LAT_LON_REQUEST_FAIL";
